### ISSUE TITLE
Returning Errors from useInsertMutation

### ISSUE THREAD

**Issue by drewbietron** [psteinroe/supabase-cache-helpers#105]
I am not seeing a way to return errors from using the `useInsertMutation.`. Since the Supabase client doesn't throw an error, and rather returns an error key in the response, I am not seeing that same error key returned using `[insert]` per the `useInsertMutation` instructions.

Any tips on how to gather if a mutation was successful or not?

**Comment by drewbietron** [comment]
Thanks @psteinroe -- ended up refactoring my application to use this vs trying to get React Query to play nice.  May go back on that at some point but am appreciating your work you've done with it so far!.

While we are on mutations, do we have to pass a query key to the `mutate` function in order to refetch data after an insert?  Was not sure what was going on under the hood in order to invalidate cache keys when I need to refetch data.

**Comment by psteinroe** [comment]
@drewbietron thanks! I still want to support react-query at some point, but glad that you find it useful with SWR, too!

If you use the insert mutation, it **should** update the cache automatically. If it does not work, could you show your mutation and query hooks?

**Comment by drewbietron** [comment]
I am now getting an error `Wildcard selector is not supported` when trying to execute a mutation using the following -

```typescript
  const [insertAddress, { data: addressInsertData, error: addressInsertError }] =
    useInsertMutation(client.from("addresses"), "single", ["id"]);
```

The query on the same page is 
```typescript
  const { data: accountAddresses } = useQuery(
    client
      .from("addresses")
      .select(
        "id, address_line_one, address_line_two, address_country_code, address_name, address_city_locality, address_state_province, address_postal_code, primary_address",
        { count: "exact" }
      )
      .order("primary_address", { ascending: false }),
    "multiple"
  );
```

When I try to execute the mutation, it returns no data or error
```typescript
    await insertAddress(address);
    console.log(addressInsertError, addressInsertData); // undefined, undefined
```

**Comment by psteinroe** [comment]
@drewbietron thanks for your patience!! I will have a look why the data of the mutation is not populated. Can you confirm that the data of the query is updated properly?

Wildcard selector is not supported because the query cannot be derived since we do not have any knowledge about the columns of the table within the library. But you are not using one, and the error should not be thrown.

**Comment by drewbietron** [comment]
> @drewbietron thanks for your patience!! I will have a look why the data of the mutation is not populated. Can you confirm that the data of the query is updated properly?
> 
> Wildcard selector is not supported because the query key cannot be derived without explicitly listing the columns since we do not have any knowledge about the columns of the table. But you are not using one, and the error should not be thrown.

The data is uploaded to the database, but the `useQuery` that references that data isnt updated, nor does the mutation return any data.  I'm on the latest version of your package as well as `2.1.1` of supabase-js.  I bypassed the wildcard error whiel debugging and the mutation still doesnt return any data 🤔

**Comment by drewbietron** [comment]
@psteinroe - Is there any other SWR config that needs to be set up outside of whats mentioned in the setup of this repo in order to get mutations to return data after calling insert?

**Comment by psteinroe** [comment]
@drewbietron I am a bit flooded with work at the moment - sorry for the delay! 

Thanks for getting more details. Could you paste query + mutation for both requests? I am not able to replicate, and your table does not have any data types that might make problems. 

Best case would be if you could provide a full repro, or even create a pr with a failing test.

Thanks!

Note: I added another feature to the V1 roadmap that should help here.

**Comment by psteinroe** [comment]
fixed in v1
