### ISSUE TITLE
useSubscription keeps getting re-called every render - breaking component

### ISSUE THREAD

**Issue by jabza** [psteinroe/supabase-cache-helpers#162]
When using:
`const { status } = useSubscription(supabase.channel("any"), { event: "*", table: "coupons", schema: "public" }, ["id"]);`

In my React component, I am getting an error about this being called multiple times? It locks up the app.

`'subscribe' can only be called a single time per channel instance`

Any ideas?

Thanks!

**Comment by psteinroe** [comment]
Hey, thanks for reporting the issue! Could you provide a bit more context? Are you using the hook in other places in your app, too? Maybe even a reproduction, if you have time for it.

**Comment by jabza** [comment]
Used in one place - maybe it's because I'm using the same channel? I use it alongside a useQuery. hmm

**Comment by psteinroe** [comment]
That would be my guess. If that's true, it's something I would like to add to the documentation. Could you provide a repro, or more code snippets?

**Comment by psteinroe** [comment]
can replicate! This is an issue of `useSubscription`, because we pass the `channel` as parameter, and use the same over and over again. I will refactor this to the same API as `useSubscriptionQuery`, so that we pass the client as first arg, and the channel name as the second arg.
