### ISSUE TITLE
useUpsertMutation

### ISSUE THREAD

**Issue by e-lobo** [psteinroe/supabase-cache-helpers#215]
is it possible to use `ignoreDuplicates` or `defaultToNull` ie the [options](https://supabase.com/docs/reference/javascript/upsert) provided by supabase with [useUpsertMutation](https://supabase-cache-helpers.vercel.app/postgrest/mutations#useupsertmutation)?

**Comment by psteinroe** [comment]
oh, good point! Will add them soon.
