### ISSUE TITLE
Trigger accepts only strings

### ISSUE THREAD

**Issue by boris-arkenaar** [psteinroe/supabase-cache-helpers#229]
**Describe the bug**

With `@supabase-cache-helpers/postgrest-swr@1.0.19`.

The trigger function coming from `useUpsertMutation` and `useDeleteMutation` seems to accept only a string as its first argument.

TypeScript gives me the following error:

```
No overload matches this call.
  Overload 1 of 3, '(extraArgument: string, options?: SWRMutationConfiguration<unknown[] | null, PostgrestError, Record<string, unknown>[], string, unknown[] | null> | undefined): Promise<...>', gave the following error.
    Argument of type '{ [x: string]: unknown; }' is not assignable to parameter of type 'string'.
  Overload 2 of 3, '(extraArgument: string, options?: (SWRMutationConfiguration<unknown[] | null, PostgrestError, Record<string, unknown>[], string, unknown[] | null> & { ...; }) | undefined): Promise<...>', gave the following error.
    Argument of type '{ [x: string]: unknown; }' is not assignable to parameter of type 'string'.
  Overload 3 of 3, '(extraArgument: string, options?: (SWRMutationConfiguration<unknown[] | null, PostgrestError, Record<string, unknown>[], string, unknown[] | null> & { ...; }) | undefined): Promise<...>', gave the following error.
    Argument of type '{ [x: string]: unknown; }' is not assignable to parameter of type 'string'.
```

**Expected behavior**
Expected to be able to supply an argument to the trigger function of type `Record<string, unknown>[]`.

**Additional context**
Using the latest versions of all dependencies. Version `1.0.19` of `@supabase-cache-helpers/postgrest-swr`.

**Comment by psteinroe** [comment]
thanks for opening the issue. what supabase-js versions are you using?

**Comment by boris-arkenaar** [comment]
Thanks for the quick response @psteinroe 

The dependencies I've installed:

```
    "swr": "2.2.0",
    "@supabase/supabase-js": "2.26.0",
    "@supabase/postgrest-js": "1.7.1",
    "@supabase-cache-helpers/postgrest-swr": "1.0.19",
```

**Comment by psteinroe** [comment]
> Thanks for the quick response @psteinroe
> 
> The dependencies I've installed:
> 
> ```
>     "swr": "2.2.0",
>     "@supabase/supabase-js": "2.26.0",
>     "@supabase/postgrest-js": "1.7.1",
>     "@supabase-cache-helpers/postgrest-swr": "1.0.19",
> ```

can you by any chance provide a repro? I am using the exact same versions, and do not have this type error. The sir example in this repo is also using the same versions, and the type error is not thrown.

**Comment by boris-arkenaar** [comment]
At the moment I cannot reproduce the error anymore. I just moved from `npm` to `pnpm` and the type error is gone. Not saying `npm` was the problem, I have no idea what caused it. Happy that it works now. In case it comes back I'll try to make a repro. Sorry for the disturbance and thanks for the support!

**Comment by boris-arkenaar** [comment]
No, still got it unfortunately. I'll try and make a repro.

**Comment by psteinroe** [comment]
I think I can replicate, will take a look asap.

**Comment by psteinroe** [comment]
yep, messed up the types. Will publish a fix tomorrow.

**Comment by psteinroe** [comment]
still not fixes. investigating further...

**Comment by psteinroe** [comment]
the culprit is actually an update to `swr`: https://github.com/vercel/swr/pull/2669. publishing a fix soon.

**Comment by boris-arkenaar** [comment]
Amazing you're able to replicate. I tried to replicate in a new repo, but didn't manage to get the error.
Let me try the fix you made. Thanks for picking this up so quickly!
