### ISSUE TITLE
Update mutation SWR typing returns a non-function variable

### ISSUE THREAD

**Issue by mcornielje090404** [psteinroe/supabase-cache-helpers#237]
When using useUpdateMutation with the latest version of @supabase-cache-helpers/postgrest-swr the trigger returned is not a function that can be called. This causes issues with typescript and therefore build errors.

[Here is an example of a repo with a broken implementation ](https://github.com/mcornielje090404/supabase-cache-helpers-test)

^ This repo provides a .env.example and all the SQL required in an Example.sql file to be used in Supabase to create a DB that interacts with the repo's setup. 

**Expected behavior**
The update trigger returned from useUpdateMutation should be a callable function using typescript

**Comment by mcornielje090404** [comment]
Of note, in that repo I also have issues using the 'update' function defined as it says 'Missing value for primary key id' even though I am passing the id into the update function

**Comment by psteinroe** [comment]
hey! thanks for the repro. [this](https://github.com/mcornielje090404/supabase-cache-helpers-test/blob/ed4abdb7f338c3f3af014d916fcc950d10a1644a/supabase-cache-helpers-test/lib/useUpdateData.ts#L40) is not the correct usage. please refer to the [documentation](https://supabase-cache-helpers.vercel.app/postgrest/mutations#useupdatemutation).

also, I would recommend not wrapping the hooks in another hook. just use it directly in your component.

**Comment by mcornielje090404** [comment]
> hey! thanks for the repro. [this](https://github.com/mcornielje090404/supabase-cache-helpers-test/blob/ed4abdb7f338c3f3af014d916fcc950d10a1644a/supabase-cache-helpers-test/lib/useUpdateData.ts#L40) is not the correct usage. please refer to the [documentation](https://supabase-cache-helpers.vercel.app/postgrest/mutations#useupdatemutation).
> 
> 
> 
> also, I would recommend not wrapping the hooks in another hook. just use it directly in your component.
> 
> 
> 
> 

The hook wrapping is because the function was adopted from another repo and would not be the primary method I would use for standard integration. I am aware there may be issues with the method however, looking at the documentation it appears as though there shouldn't be the type error that I face in which the update function is returning as a non-callable variable. Is there something definitive I am doing to cause that issue?

**Comment by mcornielje090404** [comment]
> hey! thanks for the repro. [this](https://github.com/mcornielje090404/supabase-cache-helpers-test/blob/ed4abdb7f338c3f3af014d916fcc950d10a1644a/supabase-cache-helpers-test/lib/useUpdateData.ts#L40) is not the correct usage. please refer to the [documentation](https://supabase-cache-helpers.vercel.app/postgrest/mutations#useupdatemutation).
> 
> 
> 
> also, I would recommend not wrapping the hooks in another hook. just use it directly in your component.
> 
> 
> 
> 

Hello, thanks for the prompt reply. I am aware that the hook wrapping is not ideal and it wouldn't be the general way I would do it however I ripped this code out of another repo I'm working on. The issue is still outstanding if why the update trigger retired by useUpdateMutation is not a callable function. Is there something definitive I'm doing that could be causing this? The documentation does not show actually use of the update trigger.

**Comment by psteinroe** [comment]
Ah yes, you are right! Will add it. The update trigger can be called as 

```
await update({... your object})
```

Note that the object needs to include a value for all primary keys of the relation you are updating.

**Comment by mcornielje090404** [comment]
Hello, sorry for the late reply. All implementations on the example repo have been fixed and yet build errors are still occurring as a result of the typing errors on useUpdateMutation. It continues to think. that the trigger returned is not a callable function. I can confirm that this error is not present on the useInsertMutation.
