### ISSUE TITLE
Use `eq` on `rpc` TS error

### ISSUE THREAD

**Issue by boris-arkenaar** [psteinroe/supabase-cache-helpers#248]
**Describe the bug**
Typescript doesn't allow to use `eq` on an `rpc` call, while the code works as expected.

**To Reproduce**
Run

```typescript
useQuery(
  client
    .rpc('get_special')
    .select('id, name')
    .eq('id', id)
);
```

On `eq` typescript says:

```
Property 'eq' does not exist on type 'PostgrestTransformBuilder<{ Tables: { special: { Row: { id: string; name: string; }; Insert: { ...; }; Update: { ...; }; Relations...'.ts(2339)
```

**Expected behavior**
I still get an array returned with one object, the one with the id I filtered for. I expect typescript to not give me any errors on this.

**Additional context**
The `get_special` db function has a return type of `TABLE(id uuid, name text)`.

**Comment by psteinroe** [comment]
@boris-arkenaar thanks for opening the issue! are you sure that this is an issue with cache helpers, and not with `@supabase/supabase-js`? the error seems to be pointing at `client.rpc('get_special').select('id, name')`, and not at `useQuery`.

**Comment by boris-arkenaar** [comment]
Yes, you're right. I realized that as well. My apologies. Will look into it when I'm back at my computer.

**Comment by boris-arkenaar** [comment]
Haven't been able to do further investigations, but this issue should be closed.
