### ISSUE TITLE
SSR & Supabase Cache Helpers

### ISSUE THREAD

**Issue by jamescqcampbell** [psteinroe/supabase-cache-helpers#261]
**Is your feature request related to a problem? Please describe.**

I am working with NextJS and would like to use SSR to provide fallback data to this library and as such render the page with data already present. 

**Describe the solution you'd like**

I would like to be able to wrap supabase cache helpers in a server component. This would take a query as its argument and use this to request server side data. It would then pass the query builder and an encoded cache key down to the client component as props, which would be wrapped in an SWRConfig provider to provide fallback data. The query could then be used in useQuery on the client side and the keys would match. 

Have you had any initial thoughts in this direction? Your library is incredible useful so far and this feels like a missing piece. 

**Describe alternatives you've considered**

I have tried to import PostgrestParser & encode @supabase-cache-helpers/postgrest-swr and then parse my supabase query in a server component and generate a cache key. However, because of the use of state in PostgrestParser it is not possible to do this on the server. Ideally I'd then like to use the PostgrestBuilder in useQuery with my browser supabase client rather than the server supabase client.

I have tried writing a separate wrapper for each useQuery but the number of different components multiplies and it doesn't feel like a maintainable pattern. Having the same query in two places is a pain when updating one or the other and it seems simpler to me to find a way to serialise the key and somehow the builder and pass it from server to client.

Then I can have one generic wrapper I reuse and only the query and config will differ.

**Additional context**
 N/a

**Comment by psteinroe** [comment]
Sorry for the late reply, and thanks for looking into this! Could you share a bit of code? Would be interesting to see. 

At the moment, I think that this has to be solved on framework level. React query for example recently published a [new experimental package](https://tanstack.com/query/v5/docs/react/examples/react/nextjs-suspense-streaming). This would enable us to add a adapter without the hustle of manually passing props around. I am also [eagerly awaiting](https://github.com/vercel/next.js/discussions/50043) a few api improvements to the NextJS mutations api that would enable a proper nextjs adapter.

Of course, the fallback data bug is unrelated to this. I will fix it next week.

**Comment by psteinroe** [comment]
what do you think of leveraging fallback data or initial data instead? 

- define a common buildQuery function that builds the query and returns the supabase client 
- Make query server side using the returned supabase client, and pass data to client component  
- in client, build the supabase client using the same function, and set initial data from props

This should have the desired outcome without deserialising the key.

**Comment by Feel-ix-343** [comment]
I'm very interested in this. Figuring out composable and elegant data fetching for server components has been a nightmare for me. 

(this may be irrelevant) Right now, what I have settled on is using a client component with props matching a global store's type which populates the store, fetching data using supabase in a server component and passing it as props to this client component, then all client components (that need optimistic data) under the server component use the data through the store. When mutations are made, I run an optimistic update on the store and call a server action that calls supabase and revalidatesCache. 

It would be great to not have to write both a supabase mutation call and logic for updating the store. This makes this package quite appealing. However, SSR (which is important to me) still seems quite complex. 

Is there any hope for this in this package? Could the  (Also why is this issue closed?)

**Comment by psteinroe** [comment]
> Is there any hope for this in this package? Could the (Also why is this issue closed?)

because the original question was about fallbackData, which is fixed. lets reopen.

to answer your first question:

> At the moment, I think that this has to be solved on framework level. React query for example recently published a [new experimental package](https://tanstack.com/query/v5/docs/react/examples/react/nextjs-suspense-streaming). This would enable us to add a adapter without the hustle of manually passing props around. I am also https://github.com/vercel/next.js/discussions/50043 a few api improvements to the NextJS mutations api that would enable a proper nextjs adapter.

I will implement a proper adapter as soon as any of these become available.

**Comment by psteinroe** [comment]
hey everyone, since it will most likely take a while before a nextjs adapter becomes possible, I was thinking about providing helpers that would make this easier for React Query and SWR. 

The relevant pieces of documentation are here:
- react query: https://tanstack.com/query/v5/docs/react/guides/advanced-ssr
- swr: https://swr.vercel.app/docs/with-nextjs

Since I do not ssr and react query in production, I would like to get some feedback on the api design. 

**React Query**
As of now I think we are just missing a wrapper around `prefetchQuery` that could look like this:
```ts
import { prefetchQuery } from '@supabase-cache-helpers/react-query'

...

export async function getStaticProps() {
  const queryClient = new QueryClient()

  await prefetchQuery(queryClient, supabase.from('table').select(...));

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  }
}
```

**SWR**
For swr, we could provide a helper that returns the fallback data in an object with key and value, so that you could do

```ts
 export async function getStaticProps () {
  // `getStaticProps` is executed on the server side.
  const article = await getArticleFromAPI()
  return {
    props: {
      fallback: {
        ...(await fetchFallbackData(supabase.from('table').select(...)))
      }
    }
  }
}
```

or

```ts
 export async function getStaticProps () {
  // `getStaticProps` is executed on the server side.
  const article = await getArticleFromAPI()
  return {
    props: {
      fallback: await fetchFallbackData([supabase.from('tableA').select(...), supabase.from('tableB').select(...)])
    }
  }
}
```

wdyt?

**Comment by psteinroe** [comment]
> For me the key pain-point is managing the way the new nextjs app router splits server and client components and the move away from the getStaticProps examples above. 

For app router, the example would look similar: put the `fetchFallbackData` in a Server Component, and pass it as a prop the the client component. You can find an example in the docs of Tanstack Query:
```tsx
export default async function PostsPage() {
  const queryClient = new QueryClient()

  await queryClient.prefetchQuery({
    queryKey: ['posts'],
    queryFn: getPosts,
  })

  return (
    // Neat! Serialization is now as easy as passing props.
    // HydrationBoundary is a Client Component, so hydration will happen there.
    <HydrationBoundary state={dehydrate(queryClient)}>
      <Posts />
    </HydrationBoundary>
  )
}
```

But this also means that 
>  ensuring the fallback query always equals the client side query in every component in two files

is not really something where we can improve dx I fear. You will always have to define two queries, especially since client-side, you might be adding dynamic filters etc to it.

But I agree, I think a flexible api like `fetchFallbackData(supabase.from()): [string, Data]` would be preferable.

**Comment by Feel-ix-343** [comment]
I believe we can use server actions to use the same fetching function! This is because actions can return serializable data. Create the function in a different file with a "use server" below the header and use the function in the server and client component.

**Comment by psteinroe** [comment]
> I believe we can use server actions to use the same fetching function! This is because actions can return serializable data. Create the function in a different file with a "use server" below the header and use the function in the server and client component.

that's interesting. can you provide a code snippet?

**Comment by Feel-ix-343** [comment]
Yes I believe they would work the same because the server action always runs on the sever no matter the calling context. 

As for the example, it would be like this
```
// actions.ts
async function databasething(filter: string) {
    "use server"
   // what ever this syntax is idk
    const supabase = createServerActionClient({cookies})

    return supabase.select ... with filter
}

// page.tsx
export default async function() {

    // query with the server action

    return clientcomponent and react query wrapper

}

// clientcomponent.tsx
import {databasething} from "./actions"
export default function () {
    react query with the databasething

    ...
}

```

boom no code duplication.

**Comment by psteinroe** [comment]
docs:

SWR: https://supabase-cache-helpers.vercel.app/postgrest/ssr/swr
React Query: https://supabase-cache-helpers.vercel.app/postgrest/ssr/react-query
