### ISSUE TITLE
Queries don't respect fallbackData

### ISSUE THREAD

**Issue by nanderLP** [psteinroe/supabase-cache-helpers#262]
**Describe the bug**
When providing `fallbackData` to the options of a `useInfiniteOffsetPaginationQuery` hook, currentPage still returns an empty Array on first render

**To Reproduce**
There's no test for using the fallbackData field.
Basic code to reproduce
```tsx
const {
  currentPage,
  isLoading,
  nextPage,
  previousPage,
  pageIndex,
} = useInfiniteOffsetPaginationQuery(client.from("test").select(), {
  fallbackData: ["test"],
});

console.log(currentPage) // returns [] instead of ["test"]
```

**Expected behavior**
`currentPage` should return ["test"] on first render

**Comment by nanderLP** [comment]
I notice the same problem with useQuery, maybe it's a more fundamental bug?

**Comment by iamchubko** [comment]
Experiencing the same issue
```
"@supabase-cache-helpers/postgrest-swr": "^1.1.6",
```

**Comment by psteinroe** [comment]
I will take a look at this soonish. sorry for the long response time. The reason of this will most likely be that the pagination queries do internally have a different data model than what is returned. I need to add a transformer to the fallbackData for it to work as expected.
