### ISSUE TITLE
How to use prefetch for queries

### ISSUE THREAD

**Issue by das-monki** [psteinroe/supabase-cache-helpers#263]
I'm not well versed in js-land, but it seems currently it's not possible to prefetch queries, is that right?

I was looking if it's possible to use `encode` directly to get the query-key (and use that to prefetch queries), but I didn't find a way since encode is not exported.

Soo is there a way to use prefetch with the current version?

Ps.: Thanks for the library! I just recently discovered react-query, and with you implementing even subscriptions, it makes my life easier. 😊

**Comment by psteinroe** [comment]
hey @das-monki, 

can you give an example on that you are trying to achieve? I assume it is a duplicate of #261 and #262?

**Comment by psteinroe** [comment]
this is not possible :)
