### ISSUE TITLE
How to update correctly?

### ISSUE THREAD

**Issue by vrilcode** [psteinroe/supabase-cache-helpers#273]
I am trying to update a boolean value "archiviert" of a record by clicking on a button. I tried to follow the docs; please see my minimal example below. PostgREST backend is updating properly, but the returned data is not put into `data`. As far as I understand supabase-cache-helpers, it should be updated automatically by matching cache keys? I also tried to wrap `update()`-call with `mutate()`-call. Then it is reflecting changes in `data`, but it's fetching the updated record again (additional `GET` request), which is unnecessary.

```javascript
import { useQuery, useUpdateMutation } from '@supabase-cache-helpers/postgrest-swr'
import { client } from '../../lib/client'

export default function Page() {
  const { data, mutate } = useQuery(
    client
      .from('bn')
      .select('id,kurzname,archiviert')
      .eq('id', 2)
      .single(),
    {
      revalidateOnFocus: false,
      revalidateOnReconnect: false,
    }
  )

  const { trigger: update } = useUpdateMutation(
    client.from('bn'),
    ['id'],
    'id,kurzname,archiviert',
    {
      onSuccess: () => console.log('Success!'),
    }
  );

  return (
    <div>
      {JSON.stringify(data)}<br/>
      <button onClick={() => {
        update({
          id: 2,
          archiviert: !data.archiviert
        })
      }}>Toggle "archiviert"</button>
    </div>
  )
}
```

**Comment by psteinroe** [comment]
Hey! are you on the latest version? And did you [disable all automatic revalidation mechanisms](https://supabase-cache-helpers.vercel.app/configuration)? 

you should even be able to pass `null` here. cache helpers will scan the cache and build the select statement automatically.
```tsx
  const { trigger: update } = useUpdateMutation(
    client.from('bn'),
    ['id'],
    null, // can be null
    {
      onSuccess: () => console.log('Success!'),
    }
  );
```

**Comment by vrilcode** [comment]
I use `@supabase-cache-helpers/postgrest-swr` version 1.1.6. Any revalidation is disabled:
```
revalidateOnFocus: false,
revalidateOnReconnect: false,
revalidateIfStale: false
```

 If I use `update(...)` only, only `PATCH` request is sent to PostgREST, but response is empty and doesn't contain the updated data. If I use `mutate(update(...))`, `PATCH` request is sent und `GET` request with updated data follows immediately. Couldn't find out how to have a single `PATCH` request with updated data as response.

**Comment by psteinroe** [comment]
hey @vrilcode,

can you share a bit of code or a repro? 

you can find a working example in [demos/swr](https://github.com/psteinroe/supabase-cache-helpers/tree/main/examples/swr) (deployed [here](https://supabase-cache-helpers-swr.vercel.app/use-infinite-scroll-query)). Note that there is an extra GET request, but it's from `useSubscriptionQuery`.

**Comment by vrilcode** [comment]
Please see below. Unfortunately I don't have a repo. Test table is called "table" and consists just of two columns "id" (serial) and "value" (text). One row with "id" = 1 should be updated.

```javascript
import { useQuery, useUpdateMutation } from '@supabase-cache-helpers/postgrest-swr'
import { client } from '../../lib/client'

export default function Page() {
  const { data, mutate } = useQuery(
    client
      .from('table')
      .select('id,value')
      .eq('id', 1)
      .single(),
    {
      revalidateOnFocus: false,
      revalidateOnReconnect: false,
      revalidateIfStale: false
    }
  )

  const { trigger: update } = useUpdateMutation(
    client.from('table'),
    ['id'],
    null,
    {
      onSuccess: () => console.log('Success!'),
    }
  );

  return (
    <div>
      {JSON.stringify(data)}<br/>
      <button onClick={async () => {
        await mutate(update({
          id: 1,
          val: `Test ${Date.now()}`
        }))
      }}>Update value</button>
    </div>
  )
}
```

**Comment by psteinroe** [comment]
closing this, please reopen if you still have problems :)
