### ISSUE TITLE
migrate to Bun

### ISSUE THREAD

**Issue by psteinroe** [psteinroe/supabase-cache-helpers#284]
**Is your feature request related to a problem? Please describe.**
Since this is a small-enough project, we should migrate to bun to save time (and for the sake of it, of course).

**Describe the solution you'd like**
Migrate to bun for the package management, and as a test runner. 

The latter could require refactoring a bunch of tests, due to missing mock features in the bun test runner.

**Comment by corners2wall** [comment]
Assign to me pls. I will try. It's good challenge

**Comment by corners2wall** [comment]
@psteinroe  after research I'm blocked by this issue: [turborepo doesn't support bun :( ](https://github.com/vercel/turbo/issues/4762)

**Comment by psteinroe** [comment]
@corners2wall thanks for the research. Given the nature of the issue, this is most likely a few months off. Let's keep this issue open and regularly check for their progress.

**Comment by corners2wall** [comment]
@psteinroe  totally agree with you

**Comment by pontusab** [comment]
turbo now have beta support for bun https://x.com/turborepo/status/1702791416672387094?s=46&t=EsyqrpgYWcCvn97nnTxwww

**Comment by psteinroe** [comment]
@corners2wall are you still interested in taking this?

**Comment by corners2wall** [comment]
@psteinroe yes, I'll do it this week

**Comment by psteinroe** [comment]
The next version of bun will support module mocking, which will make the migration of the tests way simpler: https://x.com/jarredsumner/status/1716802352253112722?s=46&t=6in1CtH0XPGZTdWeLKr4gg

**Comment by aggmoulik** [comment]
Hey @psteinroe I saw your tweet on X platform and I would love to work on bun support.

**Comment by psteinroe** [comment]
@aggmoulik awesome, thanks! Let me know if you need any support.

**Comment by psteinroe** [comment]
migrated to vitest instead of bun test due to better maturity and dx
