### ISSUE TITLE
Support for `@tanstack/react-query` v5

### ISSUE THREAD

**Issue by jcwillox** [psteinroe/supabase-cache-helpers#292]
**Describe the solution you'd like**

Seeing as [@tanstack/react-query v5](https://tanstack.com/query/v5/docs/react/installation) is now in the release candidate stage, now might be a good time to start migrating the codebase to support it and even possibly release a beta with v5 support.

This library is super helpful 👍, but react-query v5 has some really useful features for nextjs app dir, that I'd like to take advantage of, and some improvements to suspense and optimistic updates.

**Describe alternatives you've considered**

Doing it myself 😄, honestly I might, doesn't seem to be a too difficult migration, but considering you have more experience with this codebase it will probably be a lot quicker.

**Additional context**

https://tanstack.com/query/v5/docs/react/guides/migrating-to-v5

**Comment by psteinroe** [comment]
thanks for opening the issue. seems very doable. since I don't want to end up with a table "install v1 for v4, and v2 for v5" etc., I would prefer to wait for the final release before we merge it. the migration itself will be not a lot of effort.

**Comment by jcwillox** [comment]
Great to hear, and fair enough 😄
I'll be happy to test out the migration as well once it is ready 👍
