### ISSUE TITLE
Duplicate item in query after using upsert mutation

### ISSUE THREAD

**Issue by stevebyatt10** [psteinroe/supabase-cache-helpers#329]
**Describe the bug**
When using `useQuery` or `useInfiniteOffsetPaginationQuery` and then modifying a row with `useUpsertMutation`, the row is updated and moved to the bottom of the list but the first item is now a duplicate of the newly updated row. The size of the data array remains the same and so one row is missing with the duplicate in its place.

It seems to be similar to this issue https://github.com/psteinroe/supabase-cache-helpers/issues/59 but I don't use subscriptions.

**To Reproduce**
If possible, open a PR with a failing test. Otherwise, describe how to reproduce the behavior:

```
const { trigger: upsert } = useUpsertMutation(
    supabase.from("table"),
    ["id, foo_id"],
    null,
    {
      revalidate: true,
    }
  );
  
const query = supabase
    .from("table")
    .select("id, foo_id, name")
    .eq("foo_id", foo?.id);

const { data } = useQuery(foo ? query : null);
```

I've tried with revalidate set to true and false, also by ordering of creation date but I am getting the same result

**Expected behavior**
Item to be updated in the list with no duplicate entry.

**Comment by psteinroe** [comment]
thanks for reporting the issue. Is this about tables with two primary keys, and a query on just one of them? Or is the reproduction example random?

**Comment by stevebyatt10** [comment]
> thanks for reporting the issue. Is this about tables with two primary keys, and a query on just one of them? Or is the reproduction example random?

Yeah correct, I just tested now with only id passed in as the primary key field for the upsert mutation and is now working as expected. So I'm not sure if it was an issue form my end but `useUpsertMutation` mentions `An array of primary key column names for the table.` so i assumed it requires all the primary keys passed in.

```
const { trigger: upsert } = useUpsertMutation(
    supabase.from("table"),
    ["id"],
    null,
    {
      revalidate: true,
    }
  );
  ```

**Comment by psteinroe** [comment]
> > thanks for reporting the issue. Is this about tables with two primary keys, and a query on just one of them? Or is the reproduction example random?
> 
> Yeah correct, I just tested now with only id passed in as the primary key field for the upsert mutation and is now working as expected. So I'm not sure if it was an issue form my end but `useUpsertMutation` mentions `An array of primary key column names for the table.` so i assumed it requires all the primary keys passed in.
> 
> ```
> const { trigger: upsert } = useUpsertMutation(
>     supabase.from("table"),
>     ["id"],
>     null,
>     {
>       revalidate: true,
>     }
>   );
> ```

yes, if your table has two primary keys then both should be passed in the array as well as the input. so both `id` and `foo_id` are primary keys of your table? Can you pass me a minimal schema for me to reproduce?

**Comment by stevebyatt10** [comment]
```
CREATE TABLE "foo" (
  "id" integer PRIMARY KEY
);

CREATE TABLE "bar" (
  "id" integer,
  "foo_id" integer,
  "name" text,
  PRIMARY KEY ("id", "foo_id")
);

ALTER TABLE "bar" ADD FOREIGN KEY ("foo_id") REFERENCES "foo" ("id");
```

With the foo bar tables, this is how i was querying them
```
// retrieve foo object from global state
const foo = useFoo();

const { trigger: upsert } = useUpsertMutation(
    supabase.from("bar"),
    ["id, foo_id"],
    null
  );
  
const query = supabase
    .from("bar")
    .select("id, name")
    .eq("foo_id", foo?.id);

const { data } = useQuery(foo ? query : null);
```

**Comment by psteinroe** [comment]
hey @stevebyatt10, I have added a test to try and replicate your issue. https://github.com/psteinroe/supabase-cache-helpers/pull/331

Unfortunately, it works. Can you find any difference to your code?

**Comment by stevebyatt10** [comment]
Apologies for the late reply, this is unfortunately a mistake on my end. 

```
 const { trigger: upsert } = useUpsertMutation(
    supabase.from("bar"),
    ["id, foo_id"], <- 1 string
    null
  );
```

I can confirm this does work when actually passing 2 strings. 

Thanks for taking a look into this once again.

**Comment by psteinroe** [comment]
> Apologies for the late reply, this is unfortunately a mistake on my end.
> 
> ```
>  const { trigger: upsert } = useUpsertMutation(
>     supabase.from("bar"),
>     ["id, foo_id"], <- 1 string
>     null
>   );
> ```
> 
> I can confirm this does work when actually passing 2 strings.
> 
> Thanks for taking a look into this once again.

ahh good catch! no worries, its always good to add more tests. :)
