### ISSUE TITLE
[React Query] How to revalidateTables properly?

### ISSUE THREAD

**Issue by stefanbuesch** [psteinroe/supabase-cache-helpers#365]
**Is your feature request related to a problem? Please describe.**
 I'm trying to manually refetch some keys with "revalidateTables" and I'm not sure if I'm on the right track? Are there any examples for using "revalidateTables" properly?

**Describe the solution you'd like**
I need the modules table to refetch after the mutation.

```
const { mutateAsync: update } = useUpdateMutation(
    supabase.schema('lms').from('modules'),
    ['id'],
    null,
    {
      onSuccess: () => {
        setSuccess(true);
      },
      onError: (error) => {
        return error;
      },
      revalidateTables: [
        {
          schema: 'lms',
          table: 'modules',
        },
      ],
    }
  );

  const updateModuleData = async (moduleData: Database['lms']['Tables']['modules']['Insert']) => {
    await update(moduleData);
  };

  return updateModuleData; 
}

**Comment by j1mie** [comment]
I'm in a similar boat — trying out revalidateTables and revalidateRelations but can't seem to get related queries to update

**Comment by psteinroe** [comment]
your code looks fine. maybe there is a bug here, will take a look. thanks for reporting!

**Comment by psteinroe** [comment]
there are two issues here:
- it was not working for swr due to a bug that is fixed in the linked pr
- because of a design fault, you need to pass something as the query. otherwise `upsertItem` is never called. I may fix this in a future release. until then the workaround is to just pass anything but `null`:

```ts
const { mutateAsync: update } = useUpdateMutation(
    supabase.schema('lms').from('modules'),
    ['id'],
   'id', // <-- not null!
    {
      onSuccess: () => {
        setSuccess(true);
      },
      onError: (error) => {
        return error;
      },
      revalidateTables: [
        {
          schema: 'lms',
          table: 'modules',
        },
      ],
    }
  );
```

**Comment by ayeshabasit** [comment]
Hey, I'm on the latest version with React Query and my table does not get revalidated. There is a database trigger that creates a record in the `persons` table before a `cloud_contributor` is created. Maybe I have misunderstood the purpose of the `revalidateTables` feature and should find a way to do a complete refetch. If anyone has any suggestions on how to do that, please let me know! 

`import useSupabase from '@/hooks/use-supabase';
import { useInsertMutation } from '@supabase-cache-helpers/postgrest-react-query';

function useInsertCloudContributorMutation() {
  const client = useSupabase();
  return useInsertMutation(
    //@ts-ignore
    client.from('cloud_contributors'),
    ['id'],
    'id',
    {
      revalidateTables: [
        {
          table: 'persons',
        },
      ],
    }
  );
}`

**Comment by psteinroe** [comment]
Hey @ayeshabasit, can you post all involved queries and mutations?

**Comment by ayeshabasit** [comment]
Thanks for responding @psteinroe!

To create:
```
import useSupabase from '@/hooks/use-supabase';
import { useInsertMutation } from '@supabase-cache-helpers/postgrest-react-query';

function useInsertCloudContributorMutation() {
  const client = useSupabase();
  return useInsertMutation(
    //@ts-ignore
    client.from('cloud_contributors'),
    ['id'],
    'id',
    {
      revalidateTables: [
        {
          table: 'Persons',
        },
      ],
    }
  );
}

export default useInsertCloudContributorMutation;
```
To fetch:
```
import type { SupabaseClient } from '@supabase/supabase-js';
import type { CloudContributors } from '@/schema/database.types';

export function getCloudContributorsAndPersons(
  client: SupabaseClient,
  cloudId: string
) {
  return client
    .from<any, CloudContributors>('cloud_contributors')
    .select(
      'id,created_at,email,cloud_id, person:persons(id, created_at, user_id, first_name, last_name, gender, dob, dod, full_name, stripe_customer_id, contact_email, is_active_user)'
    )
    .eq('cloud_id', cloudId)
    .order('created_at', { ascending: false });
}
```

Postgres Trigger:
```
-- create a trigger to insert a person record if person record does not exist into cloud contributors for that email FIRST
create function public.handle_cloud_contributor_person_record()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.persons (contact_email, is_active_user)
  values (new.email, false)
  on conflict(contact_email)
  do nothing;
  return new;
end;
$$;

-- then insert cloud contributor record
create trigger on_cloud_contributor_created
  before insert on public.cloud_contributors
  for each row execute procedure public.handle_cloud_contributor_person_record();
```

**Comment by ayeshabasit** [comment]
@psteinroe I'm still stuck with this. Not sure where to go from here!

**Comment by psteinroe** [comment]
hey @ayeshabasit , sorry! It got lost because this issue is already closed.

your query looks good to me. it should automatically revalidation even without revalidate tables.

since this is a very basic use case and it's working in tests and in production for me, would you be so kind to create a full repro, oder open a pr with a failing test?
