### ISSUE TITLE
Breakout and export useReactQuery options for use outside of hooks

### ISSUE THREAD

**Issue by ThatGuySam** [psteinroe/supabase-cache-helpers#373]
**Is your feature request related to a problem? Please describe.**
I've been frequently needing a way to trigger queries outside of hooks, for example, inside conditional logic or 

**Describe the solution you'd like**
I'd like to be able to get back the query options as opposed the hook method itself so that I can use plain async/await JavaScript with methods like fetchQuery. 
fetchQuery method Docs - https://tanstack.com/query/v4/docs/reference/QueryClient#queryclientfetchquery

Basically, abstract the object passed into useReactQuery into a function like `buildQueryOptions` that can be exported instead. 

Also, this means my async functions will share the same cache with @supabase-cache-helpers

**Describe alternatives you've considered**
I've tried using hooks for everything but I have handle the hooks always being not ready/loading state since they always have to return a value. 

I can manually invalidate the cache by importing the respective `encode` function but it would be nicer to have a single thing that I can always use. 
```ts
import { encodeQueryToCacheKey, queryClient } from '~/src/lib/query'

...

// Manually invalidate the discovery profile and full profile queries if cache helpers don't work
export async function invalidateProfile ( profileId: string ) {
    const discoverProfileQuery = buildSingleProfileQuery( profileId )
    const fullProfileQuery = buildSingleFullProfileQuery( profileId )
    
    await Promise.all( [
        queryClient.invalidateQueries( encodeQueryToCacheKey( discoverProfileQuery, false ) ),
        queryClient.invalidateQueries( encodeQueryToCacheKey( fullProfileQuery, false ) )
    ] )
}
```

**Additional context**

I currently have found a work around but this will likely break at some point from an update: 
```ts
import { createUrlFetcher } from '@supabase-cache-helpers/storage-core'
import type { useFileUrl } from '@supabase-cache-helpers/storage-react-query'
import { encode as encodeStorageKey } from '@supabase-cache-helpers/storage-react-query'

import { queryClient } from '~/src/lib/query'

type UseFileUrlParameters = Parameters<typeof useFileUrl>

function buildStorageQueryOptions ( ...params: UseFileUrlParameters ) {
    const [
        fileApi,
        path,
        mode = 'private' as const,
        config = {}
    ] = params

    return {
        queryKey: encodeStorageKey( [ fileApi, path ] ),
        queryFn: () => createUrlFetcher( mode, config )( fileApi, path ),
        ...config
    }
}

// Programmatic version of useFileUrl
// so that we can use the query outside of React Hooks ala queryClient.fetchQuery()
export function queryStorage ( ...params: UseFileUrlParameters ) {
    return queryClient.fetchQuery(
        buildStorageQueryOptions( ...params )
    )
}

export function invalidateStorage ( ...params: UseFileUrlParameters ) {
    return queryClient.invalidateQueries(
        buildStorageQueryOptions( ...params ).queryKey
    )
}
```

I feel like I've read enough of the repo to do a pull request on this if desired, but let me know your thinking. 

Thanks a ton for building this. It's been a real life saver for making supabase efficient!

**Comment by psteinroe** [comment]
Hey! Thanks for the kind words and the proposal!

If you are looking to reconstruct the queryOptions, we just need to re-export the fetcher function if I am not mistaken. But you are looking for a set of helpers aren't you?

**Comment by ThatGuySam** [comment]
I do need the fetcher function but I also need the queryKey along with any `config` options. 

Ideally, I need a way to share these options between the queryClient methods as well as hooks so that they all work the same and share the same cache. 

```ts
import { useQuery } from '@tanstack/react-query'
import { queryClient } from '~/src/lib/query'


function buildStorageQueryOptions ( ...params: UseFileUrlParameters ) {
    const [
        fileApi,
        path,
        mode = 'private' as const,
        config = {}
    ] = params

    return {
        queryKey: encode( [ fileApi, path ] ),
        queryFn: () => createUrlFetcher( mode, config )( fileApi, path ),
        ...config
    }
}

// Inside React Component or Hook
const query = useQuery( buildStorageQueryOptions() )

// Inside Async function
const response = await queryClient.fetchQuery( buildStorageQueryOptions() )
const response = await queryClient.prefetchQuery( buildStorageQueryOptions() )
```

**Comment by ThatGuySam** [comment]
Whoa! That was fast! 

Thank you sir! You’re a gentleman and a scholar

**Comment by psteinroe** [comment]
I just realised your issue was about storage. I did it for postgrest only so far. Sorry about that!

**Comment by ThatGuySam** [comment]
No, you were correct. It was about both postgrest and storage. I just used storage as an example since I already had code written up for it.
