### ISSUE TITLE
useUpsertMutation / useUpdateMutation with multiple entities

### ISSUE THREAD

**Issue by jamescqcampbell** [psteinroe/supabase-cache-helpers#389]
**Is your feature request related to a problem? Please describe.**
I have an array of updates to make to cells in a table. I'd like to useUpdateMutation / useUpsertMutation on all of them in one transaction and then mutate the cache with all of them at one time.

If I do this in a piecemeal way I will end up updating the cache and triggering 5-10x the number of rerenders I'd like.

**Describe the solution you'd like**
I'd like to be able to trigger useUpsertMutation / useUpdateMutation (and useDeleteMutation) with multiple entities.

**Describe alternatives you've considered**
I've considered using supabase's library functionality to perform the updates and then manually mutate the cache. But this is still clumsy and inefficient (using some kind of for loop and still triggering lots of rerenders).

Any thoughts on a better way to manage this?

**Comment by psteinroe** [comment]
hey @jamescqcampbell, you can pass an array to `useUpsertMutation`, similar how you can pass an array in the `postgres-js` client. and in the latest version, a `useDeleteManyMutation` was released. can you specify your request a bit more?

**Comment by psteinroe** [comment]
this looks like you are not on the same postgres-js / supabase-js versions as this library. can you ensure that your versions match what is listed in the dependencies of the respective adapter?

**Comment by psteinroe** [comment]
unfortunately, supabase does frequent changes to their inner types in minor releases. this is why the same version is often required, and updating cache helpers to latest supabase-js / postgrest-js always takes some time.
