### ISSUE TITLE
Mutation Typescript types

### ISSUE THREAD

**Issue by cptlchad** [psteinroe/supabase-cache-helpers#405]
Is there something missing in my setup to have type completion inside mutations? Right now I can pretty much pass anything to the mutation and my IDE doesn't notice potential errors.

<img width="485" alt="image" src="https://github.com/psteinroe/supabase-cache-helpers/assets/94874153/fac0a4b7-27c6-4098-a690-b19ac997985d">

**Comment by uncvrd** [comment]
I'm pretty sure this has to do with the same issue I posted a few days ago #401 what moduleResolution are you using in your tsconfig.json? Hopefully we can get some thoughts from @psteinroe ....happy to help where i can

**Comment by psteinroe** [comment]
hey @uncvrd and @cptlchad, thanks for opening the issues! I guess we are missing some package json export config. Does anyone of you have experience with this? Happy to accept prs and support!

**Comment by uncvrd** [comment]
@psteinroe thanks for the PR encouragement! I took a look and it seems to be resolved by updating TS to the latest version. Hopefully this helps, let me know if you have any questions
