### ISSUE TITLE
Error when invalidating cache with useUpdateMutation and foreignTables

### ISSUE THREAD

**Issue by uncvrd** [psteinroe/supabase-cache-helpers#437]
**Describe the bug**

Hi again! Just wanted to raise a small issue I ran in to when using the `useUpdateMutation` regarding foreignTables during the cache invalidation flow where I ran in to an error when I have a query like this:

```
supabase
    .from("Collection")
    .select("id,name,imageEnding,type,CollectionFolder!inner(CollectionFolderTrack!inner(trackId))")
    .eq("CollectionFolder.CollectionFolderTrack.trackId", id)
```

Then when I utilize the `useUpdateMutation` i end up with an error that looks like this:

`Error: Unbalanced right delimiter found in string at position 85`

Which I discovered was from this `matchRecursive` in this library.

```
  const foreignTables = XRegExp.matchRecursive(
    `,${s}`,
    ',[^,]*\\(',
    '\\)',
    'g',
    {
      valueNames: {
        '0': null,
        '1': 'tableName',
        '2': 'selectedColumns',
        '3': null,
      },
    },
  ).reduce((prev, curr, idx, matches) => {
    if (curr.name === 'selectedColumns') {
      const name = matches[idx - 1].value.slice(1, -1);
      prev = { ...prev, [name]: curr.value };
    }
    return prev;
  }, {});
```

I think the regex is having issues when parsing related tables inside parentheses without a scalar property before it because if I go from:

`CollectionFolder!inner(CollectionFolderTrack!inner(trackId))`

to this one (note the id added in the !inner):

`CollectionFolder!inner(id,CollectionFolderTrack!inner(trackId))`

Then it works great. I'm not quite sure if it's an expected behavior so I just wanted to raise it up? Regex is my kryptonite so I didn't want to spend time with a change if this was expected. Let me know!

**Comment by sultson** [comment]
Hi, I encountered the same issue and indeed when the select statement contains a join statement which itself begins with another join statement, the recursive match fails.

A potential solution would be to replace `,[^,]*\\(` with `([^,\\(]+)\\(` where instead of seeking a leading comma, the table name is matched from a sequence which begins with any other character than a comma or an open parenthesis, and ends with an open parenthesis.

To keep in line with the expected form of tableName in the rest of the function, the preceding commas would added in afterwards.

```js
result = XRegExp.matchRecursive(`,${s}`, "([^,\\(]+)\\(",  "\\)", "g", {
      valueNames: {
        "0": null,
        "1": "tableName",
        "2": "selectedColumns",
        "3": null
      }
    }).map(item => {
      if (item.name === 'tableName' && item.value && !item.value.startsWith(',')) {
        item.value = ',' + item.value;
      }
      return item;
    });
```

**Comment by psteinroe** [comment]
Thanks for the issue + the proposal. If you have the time, please consider opening a pr for this. 🫶🏼
