### ISSUE TITLE
Conditional Fetching (and auth.getSession())

### ISSUE THREAD

**Issue by theSyrathos** [psteinroe/supabase-cache-helpers#464]
I have been utilising SWR because of the [conditional fetching](https://swr.vercel.app/docs/conditional-fetching). Allowing me to fetch data that is dependent on another data fetch.

Mainly 

```
const {
    data: session,
    error: userError,
    isLoading: isUserLoading,
  } = useSWR('check_login', () => supabase.auth.getSession())

  const {
    data: dashboardConfig,
    error: dashboardError,
    isLoading: isDashboardLoading,
  } = useSWR('dashboard', () =>
    supabase
      .from('user_dashboard')
      .select(
        'discord_id, theme, avatar, role, display_name, user_info!inner()'
      )
      .eq('user_info.id', session.data.session.user.id)
```

This works perfectly. I am looking at wanting to implement supabase-cache-helpers, and I have no issue converting the second useSWR to a useQuery, but it doesn't appear to be utilising the same dependency feature (not waiting for the first to get the data before running the second).

Is there a way to do the auth.getSession() using useQuery (as I get errors) and if there was would it also utilise the dependancy functionality?

**Comment by psteinroe** [comment]
you can use the `enabled` prop on react-queries useQuery to achieve conditional fetching too! 

in swr, you can pass null as the query if the condition does not match, for example 

```
useQuery(user ? supabase.from... :  null)
```

**Comment by theSyrathos** [comment]
Perfect! Thanks so much.
