### ISSUE TITLE
revalidateTables after 1.0.9 doesn't return cached data during refetch

### ISSUE THREAD

**Issue by jmwind** [psteinroe/supabase-cache-helpers#467]
**Describe the bug**

This is critical for us. We're stuck on an old version and not sure how best to proceed. Any pointers would be greatly appreciated.

We upgraded cache-helpers/swr 1.0.9 to latest 1.7.5. We noticed a lot of new re-renders and flickering in our app. After spending quite a while in the bowels of swr and comparing the behavior of the two versions we found the main difference. For a bit of background, we use quite a few rpc methods for more complex data fetching, and thus use the explicit revalidateTables when related data changes.

What we saw is that when a table revalidation occurs, the associated useQuery data is set to undefined while the refetch is in progress. Even when the cache has a copy of the data as it was previously fetched. 

To make this easier I was able to create a reproducible test case that shows our issue in a vanilla react-native + supabase app + cache-helpers.

**To Reproduce**

Here's the repo that shows the behaviour: https://github.com/jmwind/swr-cache-helpers-bug. It has a repo with easy instructions on how to dupe.

**Expected behavior**

I'd expect that if the cache has data that the revalidateTables doesn't clear the cache while revalidating. Or maybe it's calling something new in SWR. I didn't have time yet to dig into all the cache-helper implementation.

**Additional context**

Happy to help. Ping me on Twitter jmwind at any time.

**Comment by psteinroe** [comment]
hey @jmwind, thanks for the repro! are you able to pin point with what version this starts to happen? I will definitely take a look at this asap, but 1.0.9 to 1.7.5 is a big jump. If you could figure out what version this started with it would speed up my debugging a lot.

**Comment by psteinroe** [comment]
a question regarding the repro: why do you put `trips` into `revalidateTables` of the `trips` mutation? this is not something I have had in mind when implementing this, and this is can cause the flickering.

**Comment by jmwind** [comment]
@psteinroe that's just an example. What we do is we have a table profiles and a rpc/profile_extended. When profiles is mutated we revalidateTables on rpc/profile_extended. In the example repo, you can also simply remove the revalidateTable on the trips and just do profiles when trips are edited. The behaviour diff is the same. I could also add an rpc to show you how it's the same. 

For now, let me bisect by hand and pinpoint when the change happened. As you said, there are a lot of versions ;)

**Comment by jmwind** [comment]
@psteinroe ran a manual bisect with the repo I provided to show the problem. The example works up to 1.5.0, but breaks in version >1.6.0.

Happy to help troubleshoot more.

**Comment by jmwind** [comment]
Also checked that swr version is the same between cache-helpers/swr 1.5.0 and 1.6.0

```
peer swr@"^2.2.0" from @supabase-cache-helpers/postgrest-swr@1.5.0
peer swr@"^2.2.0" from @supabase-cache-helpers/postgrest-swr@1.6.0
```

**Comment by psteinroe** [comment]
this commit is the only one that makes sense as a root cause, but it actually fixed the revalidation and should not break them... I think the reason is that some other mutation is going on that sets the data to null and the revalidate then works and refetches and repopulates the data. 

https://github.com/psteinroe/supabase-cache-helpers/commit/a4d14bdb2a286d22c624767db5fe6f21a2ee6111#diff-16ab35c6c2d3521f6d299935618050664a4a1fc0fc82bc75b95a7435bd67622e

**Comment by jmwind** [comment]
Yep, that looks like it's the change. Related to revalidation, but no idea why that would trigger a different behaviour in swr. 

Here's another test I just ran. Put console.logs into useSWRHandler.revalidate and compared the output in the sample repo between 1.5.0 and 1.6.0. It's doing different work...

1.5.0: revalidate is called only once at startup, but when mutating it isn't called again

```
 LOG  START ====================
 LOG  SWR revalidate postgrest$null$public$profiles$order=id.desc&select=id%2Cfull_name%2Cusername$null$count=null$head=false$id:desc.nullsLast
 LOG  ====================
 LOG  revalidateOpts: {"dedupe": true}
 LOG  ====================
 LOG  getCache(): undefined
 LOG  ====================
 LOG  SWRGlobalState: [
  "postgrest$null$public$profiles$order=id.desc&select=id%2Cfull_name%2Cusername$null$count=null$head=false$id:desc.nullsLast"
]
 LOG  END ====================
 LOG  START ====================
 LOG  SWR revalidate postgrest$null$public$trips$order=id.desc&select=id%2Ccountry_code$null$count=null$head=false$id:desc.nullsLast
 LOG  ====================
 LOG  revalidateOpts: {"dedupe": true}
 LOG  ====================
 LOG  getCache(): undefined
 LOG  ====================
 LOG  SWRGlobalState: [
  "postgrest$null$public$profiles$order=id.desc&select=id%2Cfull_name%2Cusername$null$count=null$head=false$id:desc.nullsLast"
]
 LOG  END ====================
```

But with 1.6.0 the initial query works fine and is identical to 1.5.0. But when the mutation is called this is the output

```
START ====================
 LOG  SWR revalidate postgrest$null$public$profiles$order=id.desc&select=id%2Cfull_name%2Cusername$null$count=null$head=false$id:desc.nullsLast
 LOG  ====================
 LOG  revalidateOpts: undefined
 LOG  ====================
 LOG  getCache(): {"primaryKeys": ["id"], "revalidate": true, "revalidateTables": [{"schema": "public", "table": "profiles"}, {"schema": "public", "table": "trips"}], "schema": "public", "table": "trips"}
 LOG  ====================
 LOG  SWRGlobalState: [
  "postgrest$null$public$profiles$order=id.desc&select=id%2Cfull_name%2Cusername$null$count=null$head=false$id:desc.nullsLast"
]
 LOG  END ====================
 LOG  START ====================
 LOG  SWR revalidate postgrest$null$public$trips$order=id.desc&select=id%2Ccountry_code$null$count=null$head=false$id:desc.nullsLast
 LOG  ====================
 LOG  revalidateOpts: undefined
 LOG  ====================
 LOG  getCache(): {"primaryKeys": ["id"], "revalidate": true, "revalidateTables": [{"schema": "public", "table": "profiles"}, {"schema": "public", "table": "trips"}], "schema": "public", "table": "trips"}
 LOG  ====================
 LOG  SWRGlobalState: [
  "postgrest$null$public$profiles$order=id.desc&select=id%2Cfull_name%2Cusername$null$count=null$head=false$id:desc.nullsLast"
]
 LOG  END ====================
```

Looking at the source for swr, when the revalidateOpts don't include dedupe it will force a refetch.

**Comment by psteinroe** [comment]
I am quite sure that this worked before, but I think we have to change that part back to just `mutate(key)` without passing the options.

**Comment by jmwind** [comment]
I reverted that change with this patch, it now works fine

```
diff --git a/node_modules/@supabase-cache-helpers/postgrest-swr/dist/index.js b/node_modules/@supabase-cache-helpers/postgrest-swr/dist/index.js
index 6e03e89..59d3969 100644
--- a/node_modules/@supabase-cache-helpers/postgrest-swr/dist/index.js
+++ b/node_modules/@supabase-cache-helpers/postgrest-swr/dist/index.js
@@ -312,7 +312,7 @@ function useDeleteItem(opts) {
         cacheKeys: getMutableKeys(Array.from(cache.keys())),
         getPostgrestFilter,
         revalidate: (key) => {
-          mutate(key, __spreadProps(__spreadValues({}, opts), { revalidate: true }));
+          mutate(__spreadProps(__spreadValues({}, opts), { revalidate: true }));
         },
         mutate: (key, data) => {
           var _a;
@@ -340,7 +340,7 @@ function useMutateItem(opts) {
         cacheKeys: getMutableKeys(Array.from(cache.keys())),
         getPostgrestFilter,
         revalidate: (key) => {
-          mutate(key, __spreadProps(__spreadValues({}, opts), { revalidate: true }));
+          mutate(__spreadProps(__spreadValues({}, opts), { revalidate: true }));
         },
         mutate: (key, data) => {
           var _a;
@@ -369,7 +369,7 @@ function useUpsertItem(opts) {
         cacheKeys: getMutableKeys(Array.from(cache.keys())),
         getPostgrestFilter,
         revalidate: (key) => {
-          mutate(key, __spreadProps(__spreadValues({}, opts), { revalidate: true }));
+          mutate(__spreadProps(__spreadValues({}, opts), { revalidate: true }));
         },
         mutate: (key, data) => {
           var _a;
```

**Comment by psteinroe** [comment]
but that's not the right solution as per swr docs. the mutate is not bound but global, so we have to pass the cache key as the first argument.

**Comment by jmwind** [comment]
I haven't gotten into the swr code yet ;) 

I'd also like to know why passing the key doesn't work. As I agree, that should do the same thing. But at least we know there's a behavior diff between the two (step 1). And there's a test we could add to cache-helpers to catch this subtle change in the future. I can help and write a test case now.

**Comment by psteinroe** [comment]
can you check the pr? and a test case would be great, thanks!

**Comment by jmwind** [comment]
Do you remember why you added that? I didn't see how it was related to the test in the same commit. 

Let me help you, I'll write a test and submit. Give me 30mins.

**Comment by psteinroe** [comment]
> mutate(__spreadProps(__spreadValues({}, opts), { revalidate: true }));

this will not do anything or at least have undefined behaviour, which is why I changed it the way I did. main point of the pr was to pass the cache key as the first argument, and I assumed that if I set null or undefined as data it will just not do anything but revalidate with the options appleid as third argument. but that does not seem to be the case.

**Comment by jmwind** [comment]
@psteinroe added a test here https://github.com/psteinroe/supabase-cache-helpers/pull/470

**Comment by jmwind** [comment]
Was able to have this fail before and pass after the patch. 

Locally, the useSubscriptionQuery always fails for me but all the other tests in postgrest-swr pass reliably. Sorry if I missed something here, but tried to follow your pattern.

**Comment by jmwind** [comment]
Thanks @psteinroe! We use cache-helpers in our product a lot, so feel free to reach out if you need a hand with anything.

**Comment by psteinroe** [comment]
thanks for the sponsorship, means a lot! 🫶
