### ISSUE TITLE
[Feature Request]: Subscription Support

### ISSUE THREAD

**Issue by Marviel** [psteinroe/supabase-cache-helpers#5]
Hey! Congrats on winning the hackathon.

It would be really neat if this library would also allow you to use realtime subscriptions, and to specify a key value for each table which would be used to subscribe to future changes on that entity.

I understand that this would not allow you to subscribe to changes for the whole collection... but it would be a start!

**Comment by psteinroe** [comment]
Hey, thanks for your kind words!

I plan to add subscription support once I updated the repo (cleanup the readme, add a small roadmap etc). It should be ready by the end of the week 🙌 I will ping you to request feedback once the PR is ready.

**Comment by psteinroe** [comment]
I opened a draft pr, still needs some work though.
