### ISSUE TITLE
Type input params to mutateAsync?

### ISSUE THREAD

**Issue by samzmann** [psteinroe/supabase-cache-helpers#504]
I have a table `tickets` with rows:

```ts
id
created_at: string
created_by: string
name: string
date: string
```

Some of these fields are populated automatically via triggers in the database so I don't want the user to pass them as parameters to insert. Instead, the insert parameters should be a subtype with only the `name` and `date` fileds:
```ts
type InsertTicketPayload = Pick<
  Database['public']['Tables']['tickets']['Insert'],
  'name' | 'date'
>
```

How can I type `useInsertMutation` (or modify my global `Database` type) such that the input to `mutateAsync` is of type `InsertTicketPayload`?

**Comment by psteinroe** [comment]
Hey, 

that's a "bug" in the type generation in the supabase cli. I usually just overwrite the type when passing it into the mutation and add a comment above.

I don't think this should be fixed by cache helpers since we are relying on the generated types to be correct.

**Comment by samzmann** [comment]
Thanks for your answer.

I've been using this workaround in the meantime:
```ts
import { useInsertMutation } from "@supabase-cache-helpers/postgrest-react-query";
import { PostgrestError } from "@supabase/supabase-js";

type TicketInsert = {
 // only the fields I want on insert
}

export const useInsertTicket = ({
  onSuccess,
  onError,
}: {
  onSuccess: () => void;
  onError: (error: PostgrestError) => void;
}) => {
  const { mutateAsync } = useInsertMutation(
    supabase.from('tickets'),
    ['id'],
    null,
    { onSuccess, onError },
  );

  const insertTicket = async (ticket: TicketInsert) => mutateAsync([ticket])

  return insertTicket;
}
```

Then, every time I want to insert a `ticket`, I use the correctly typed function returned by `useInsertTicket`.
