### ISSUE TITLE
Narrowing of useQuery result seems to not work in projects with strict: true

### ISSUE THREAD

**Issue by stfnsr** [psteinroe/supabase-cache-helpers#514]
**Describe the bug**
When using useQuery (from @tanstack/react-query)  it is possible to narrow the result by checking for isPending and isError (when the query is not pending, and there is no error, there should be data)
With @supabase-cache-helpers/postgrest-react-query this doesn't seem to work when Typescript is in strict mode (after checking for isPending and isError, data is still shown as potentially being null or undefined)

I'm not sure if this is a known behaviour, but I couldn't find anything about strict mode having to be disabled in the docs.
If this is indeed a bug, I'd be happy to try and figure it out.

**To Reproduce**
I made a codesandbox to demonstrate, see line 21 in App.tsx
https://codesandbox.io/p/sandbox/xwcksp?file=%2Fsrc%2FApp.tsx%3A21%2C1-22%2C1

The example in this repo (https://github.com/psteinroe/supabase-cache-helpers/tree/main/examples/react-query) shows similar issues after enabling strict mode.

**Expected behavior**
I would expect narrowing to behave the same way it does in @tanstack/react-query

**Comment by psteinroe** [comment]
Thanks for reporting! I am not using react query myself so there could be a typing issue. It would be great if you could try to fix it.
