### ISSUE TITLE
Supabase v2 Types

### ISSUE THREAD

**Issue by drewbietron** [psteinroe/supabase-cache-helpers#53]
**Describe the bug**
I see this package uses the v2 Supabase JS client, but the types are not showing for me in my queries.  `useQuery` is returning
```typescript
const category = useQuery(
  client.from("categories").select("id, name").eq("id", props.route.params.category.id),
  "single"
);

category -> SWRResponse<unknown, PostgrestError>
```

I can confirm that the types from the client are in fact working.  That same query outside of `useQuery` returns
```typescript
const categoryQuery: PromiseLike<PostgrestSingleResponse<{
    id: string;
} & {
    name: string;
}>>
```

**Expected behavior**
Types from the query are available with the SWRResponse.

Appreciate you making this library!  I have been trying to React Query to play nicely with the new v2 types and its been a challenge.  Nice to see you tackle this already using SWR!

**Comment by drewbietron** [comment]
@psteinroe - Thanks for the response.  You mean regenerate the Supabase types and try using it again?  If it helps, I am using Supabase CLI `v1.11.2`

**Comment by psteinroe** [comment]
@drewbietron what supabase-js version are you using?

**Comment by drewbietron** [comment]
> @drewbietron what supabase-js version are you using?

`2.0.4`

Just tried updating the types once more and the issues still exists.

**Comment by psteinroe** [comment]
The problem is this this pr (https://github.com/supabase/postgrest-js/commit/4081771fd301312770fec7ec723d48f0860d7214) which was releases in `postgrest-js` `v1.1.0` which in turn was added to `supabase-js` with `2.0.4`. I am currently working on adding that upgrade to cache helpers, but it might take a few days since it is a larger breaking change. Until then, I recommend downgrading `supabase-js` again. The types should work then.

**Comment by psteinroe** [comment]
Hence, this is indeed a bug and thanks for reporting!

**Comment by drewbietron** [comment]
Appreciate you looking into it! 

Curious on your approach to how you created the cache keys?  React Query out of the box will infer the type of the Supabase client query, but the cache keys are still totally up in the air.  I was hoping there would be a way to infer the cache keys from the query itself, but it's complex.  The URL params that are sent to the rest client would be awesome, but not sure how to get them within the request, or make some sort of generic component that could do it all.  I asked about doing this in a round about way [here](https://github.com/supabase/supabase/discussions/9530#discussioncomment-3978819).

**Comment by psteinroe** [comment]
I just published a new release that uses `postgrest-js` `v1.1.0`! Please upgrade to [@supabase-cache-helpers/postgrest-swr@0.3.1](https://github.com/psteinroe/supabase-cache-helpers/releases/tag/%40supabase-cache-helpers%2Fpostgrest-swr%400.3.1).

**Comment by psteinroe** [comment]
> Appreciate you looking into it!
> 
> Curious on your approach to how you created the cache keys? React Query out of the box will infer the type of the Supabase client query, but the cache keys are still totally up in the air. I was hoping there would be a way to infer the cache keys from the query itself, but it's complex. The URL params that are sent to the rest client would be awesome, but not sure how to get them within the request, or make some sort of generic component that could do it all. I asked about doing this in a round about way [here](https://github.com/supabase/supabase/discussions/9530#discussioncomment-3978819).

lets move this to #57
