### ISSUE TITLE
Using this with Tanstack react-router (and react-query)

### ISSUE THREAD

**Issue by ChuckJonas** [psteinroe/supabase-cache-helpers#547]
**Is your feature request related to a problem? Please describe.**
I'm trying to leverage this library with Tanstack react-query and Tanstack react-router.  According to [their docs](https://tanstack.com/router/v1/docs/framework/react/guide/external-data-loading), when using react query you want to "preload" or "warm the cache".

```ts
const postsQueryOptions = queryOptions({
  queryKey: ['posts'],
  queryFn: () => fetchPosts(),
})

export const Route = createFileRoute('/posts')({
  // Use the `loader` option to ensure that the data is loaded
  loader: () => queryClient.ensureQueryData(postsQueryOptions),
  component: () => {
    // Read the data from the cache and subscribe to updates
    const {
      data: { posts },
    } = useSuspenseQuery(postsQueryOptions)

    return (
      <div>
        {posts.map((post) => (
          <Post key={post.id} post={post} />
        ))}
      </div>
    )
  },
})
```

**Describe the solution you'd like**
It's unclear how/if this can be done using this library.  There doesn't seem to be a way to call `ensureQueryData` with the query options that would match what gets passed into `useQuery` that this library exports.

**Describe alternatives you've considered**
Maybe this library isn't needed?  Or I shouldn't be preloading it in the router context?

**Comment by ChuckJonas** [comment]
ah, maybe found the solution in [the docs](https://supabase-cache-helpers.vercel.app/postgrest/ssr/react-query)... `prefetchQuery`?

**Comment by psteinroe** [comment]
That should work. If you are missing something let me know. I am not using react query myself so I can't tell if there is a helper missing.

**Comment by ChuckJonas** [comment]
On the surface, it seems to work... but I'll do some more testing to ensure it actually works.

Are you using SWR personally?  I've never loved react-query, SWR looks nice...

**Comment by psteinroe** [comment]
I am using SWR, but for no particular reason. It's internals were a bit easier to work with while building this wrapper. But I would use react query if I would start a new project. It's getting much more attention nowadays I think.
