### ISSUE TITLE
Module not found: Can't resolve 'swr' 

### ISSUE THREAD

**Issue by saendu** [psteinroe/supabase-cache-helpers#58]
**Describe the bug**
Error when no 'swr' package is installed. 
Error message: Module not found: Can't resolve 'swr'

**To Reproduce**
If possible, open a PR with a failing test. Otherwise, describe how to reproduce the behavior:
1. Follow installaction instruction
2. Run 'yarn dev'
3. Error occurs when using one of the features (useQuery, ...)

**Expected behavior**
SWR will be installed as dependency. Or installation description metiones that swr package needs to install manually.

**Comment by psteinroe** [comment]
Hey! Thanks for opening the report. SWR (as well as postgrest-js) is jut a peer dependency. If your package manager does not install those automatically, you have to add them manually to your package.json. I will add a hint to the installation instructions.
