### ISSUE TITLE
Cannot find dependencies of postgres-swr

### ISSUE THREAD

**Issue by drewbietron** [psteinroe/supabase-cache-helpers#60]
**Describe the bug**
Cant find shared dependencies when using `@supabase-cache-helpers/postgrest-swr`

**To Reproduce**
```bash
yarn add @supabase-cache-helpers/postgrest-swr
```

```typescript
import { useQuery  } from "@supabase-cache-helpers/postgrest-swr";
const query = useQuery(client.from("table").select("*", { count: "exact" }), "multiple", {
  revalidateOnFocus: false,
  revalidateOnReconnect: false,
});

index.tsx:27 Uncaught Error: Module parse failed: Unexpected token (108:19)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   return [
|     KEY_PREFIX,
>     parser.schema ?? import_postgrest_shared.DEFAULT_SCHEMA_NAME,
|     parser.table,
|     parser.queryKey,
    at ../../node_modules/@supabase-cache-helpers/postgrest-swr/dist/index.js (index.tsx:27:1)
```

**Expected behavior**
Tried to just install the swr library per the docs instructions

**Additional context**
This is within a React Native app using metro bundler within monorepo.  I also tried no-hoist'ing the package to see if it made a different and it did not.  Was also not able to import each package individually.

**Comment by psteinroe** [comment]
Hey! Thanks for opening this issue. I will try to replicate this next week, but in the meantime - did you install the peer dependencies (if your pkg manager does not install those automatically?) And what pkg manager are you using? Are you able to install and import other packages?

**Comment by drewbietron** [comment]
> Hey! Thanks for opening this issue. I will try to replicate this next week, but in the meantime - did you install the peer dependencies (if your pkg manager does not install those automatically?) And what pkg manager are you using? Are you able to install and import other packages?

I used yarn

I tried installing the root package via `yarn add supabase-cache-helpers` but that didn't work.  I'll try adding all of the shared packages individually, but wondering how it didn't just add the peer dependencies like it should?

**Comment by psteinroe** [comment]
The root package is just managing the monorepo and is not published. Please install the main packages [postgrest-swr](https://github.com/psteinroe/supabase-cache-helpers/blob/main/packages/postgrest-swr/README.md) and [storage-swr](https://github.com/psteinroe/supabase-cache-helpers/blob/main/packages/storage-swr/README.md) directly.
